// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;

/** Interface that is provided to application class. */

@SuppressWarnings("all")
public interface IPrivateMengeangebenComponentView {

  /*
   * Event Handler identifiers.
   */ 
    
  /** Event handler constant. */
  public static IWDEventHandlerId WD_EVENTHANDLER_ON_ACTION_MENGEANGEBEN_COMPLETE_EVENT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventHandlerId("onActionMengeangebenCompleteEvent", "MengeangebenComponentView", "com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponent");
  
  /** Event handler constant. */
  public static IWDEventHandlerId WD_EVENTHANDLER_ON_ACTION_MENGEANGEBEN_ERROR_EVENT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventHandlerId("onActionMengeangebenErrorEvent", "MengeangebenComponentView", "com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponent");
  
  /**
   * Provides access to the generic API of this controller.
   */
  IWDViewController wdGetAPI();


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends DataNode
  {
    private static final long serialVersionUID = 0xebec6b5a5ad637d7L;
    
    private InternalMengeangebenComponentView gen_delegate;

    IContextNode(InternalMengeangebenComponentView delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateMengeangebenComponentView.IContextNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateMengeangebenComponentView.IContextElement(gen_delegate, nodeInfo);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node. Alternatively use {@link #createAndAndContextElement()}.
     * @return an element for this node
     */
    public IPrivateMengeangebenComponentView.IContextElement createContextElement() {
      return (IPrivateMengeangebenComponentView.IContextElement)createElement();
    }

    /**
     * Creates a new <b>bound</b> element for this node.
     * @return an element for this node
     */
    public IPrivateMengeangebenComponentView.IContextElement createAndAddContextElement() {
      return (IPrivateMengeangebenComponentView.IContextElement)createAndAddElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateMengeangebenComponentView.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateMengeangebenComponentView.IContextElement currentContextElement() {
      return (IPrivateMengeangebenComponentView.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.DataNodeElement
  {
    private static final long serialVersionUID = 0xcc3d42a42542bc33L;
    
    private InternalMengeangebenComponentView gen_delegate;

    IContextElement(InternalMengeangebenComponentView delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

    // attribute "preis"
    public final static String PREIS = "preis";

    /**
     * Returns the attribute preis.
     */
    public int getPreis() {
      return gciGetInt(0);
    }

    /**
     * Sets the attribute preis.
     * @param value the new value
     */
    public void setPreis(int value) {
      gciSetInt(0, value);
    }

    // attribute "Menge"
    public final static String MENGE = "Menge";

    /**
     * Returns the attribute Menge.
     */
    public int getMenge() {
      return gciGetInt(1);
    }

    /**
     * Sets the attribute Menge.
     * @param value the new value
     */
    public void setMenge(int value) {
      gciSetInt(1, value);
    }

    // attribute "lieferzeitInTagen"
    public final static String LIEFERZEIT_IN_TAGEN = "lieferzeitInTagen";

    /**
     * Returns the attribute lieferzeitInTagen.
     */
    public int getLieferzeitInTagen() {
      return gciGetInt(2);
    }

    /**
     * Sets the attribute lieferzeitInTagen.
     * @param value the new value
     */
    public void setLieferzeitInTagen(int value) {
      gciSetInt(2, value);
    }

    // attribute "artikelnummer"
    public final static String ARTIKELNUMMER = "artikelnummer";

    /**
     * Returns the attribute artikelnummer.
     */
    public java.lang.String getArtikelnummer() {
      return gciGetString(3);
    }

    /**
     * Sets the attribute artikelnummer.
     * @param value the new value
     */
    public void setArtikelnummer(java.lang.String value) {
      gciSetString(3, value);
    }

    // attribute "waehrung"
    public final static String WAEHRUNG = "waehrung";

    /**
     * Returns the attribute waehrung.
     */
    public java.lang.String getWaehrung() {
      return gciGetString(4);
    }

    /**
     * Sets the attribute waehrung.
     * @param value the new value
     */
    public void setWaehrung(java.lang.String value) {
      gciSetString(4, value);
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

  /** Declared event handler. */
  void onActionMengeangebenCompleteEvent(IWDCustomEvent wdEvent );

  /** Declared event handler. */
  void onActionMengeangebenErrorEvent(IWDCustomEvent wdEvent );

  /** Gets controller belonging to the same component. */
  com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp.IPublicMengeangebenComponent wdGetMengeangebenComponentController();

  /** Gets action 'MengeangebenCompleteEvent'. */
  IWDAction wdGetMengeangebenCompleteEventAction();

  /** Gets action 'MengeangebenErrorEvent'. */
  IWDAction wdGetMengeangebenErrorEventAction();

  /** Enumeration of all available action event handlers. */
  public final class WDActionEventHandler extends com.sap.tc.webdynpro.progmodel.gci.impl.GCIActionEventHandlerEnum
  {
    private static final long serialVersionUID = 0xc1ccfa08105f3383L;

    public static final WDActionEventHandler MENGEANGEBEN_COMPLETE_EVENT = new WDActionEventHandler("onActionMengeangebenCompleteEvent", true, NO_PARAMETERS);

    public static final WDActionEventHandler MENGEANGEBEN_ERROR_EVENT = new WDActionEventHandler("onActionMengeangebenErrorEvent", true, NO_PARAMETERS);

    private WDActionEventHandler(String value, boolean isValidating, Object[] declaredParameters) {
      super(value, isValidating, declaredParameters);
    }
  }

  /**
   * Creates a new action for this controller.
   * @param eventHandler is the action's event handler with an appropriate signature
   * @param text is the text displayed in the UI element triggering this action
   */
  IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text);

  /**
   * Creates a new action with the given name for this controller.
   * @param eventHandler is the action's event handler with an appropriate signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text);

}
