// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;

@SuppressWarnings("all")
public interface IPublicMengeangebenComponent {

  /*
   * Event identifiers.
   */ 
    
  /** Event constant. */
  public static IWDEventId WD_EVENT_MENGEANGEBEN_COMPLETE_EVENT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventId("MengeangebenCompleteEvent", "MengeangebenComponent", "com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponent");
  
  /** Event constant. */
  public static IWDEventId WD_EVENT_MENGEANGEBEN_ERROR_EVENT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventId("MengeangebenErrorEvent", "MengeangebenComponent", "com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponent");
  
  /**
   * Provides access to the generic API of this component.
   */
  IWDComponent wdGetAPI();


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends DataNode
  {
    private static final long serialVersionUID = 0x7054de7ffe7b2a0eL;
    
    private InternalMengeangebenComponent gen_delegate;

    IContextNode(InternalMengeangebenComponent delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateMengeangebenComponent.IContextNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateMengeangebenComponent.IContextElement(gen_delegate, nodeInfo);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node. Alternatively use {@link #createAndAndContextElement()}.
     * @return an element for this node
     */
    public IPrivateMengeangebenComponent.IContextElement createContextElement() {
      return (IPrivateMengeangebenComponent.IContextElement)createElement();
    }

    /**
     * Creates a new <b>bound</b> element for this node.
     * @return an element for this node
     */
    public IPrivateMengeangebenComponent.IContextElement createAndAddContextElement() {
      return (IPrivateMengeangebenComponent.IContextElement)createAndAddElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateMengeangebenComponent.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateMengeangebenComponent.IContextElement currentContextElement() {
      return (IPrivateMengeangebenComponent.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.DataNodeElement
  {
    private static final long serialVersionUID = 0x432cc15ffa8334c2L;
    
    private InternalMengeangebenComponent gen_delegate;

    IContextElement(InternalMengeangebenComponent delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

    // attribute "preis"
    public final static String PREIS = "preis";

    /**
     * Returns the attribute preis.
     */
    public int getPreis() {
      return gciGetInt(0);
    }

    /**
     * Sets the attribute preis.
     * @param value the new value
     */
    public void setPreis(int value) {
      gciSetInt(0, value);
    }

    // attribute "Menge"
    public final static String MENGE = "Menge";

    /**
     * Returns the attribute Menge.
     */
    public int getMenge() {
      return gciGetInt(1);
    }

    /**
     * Sets the attribute Menge.
     * @param value the new value
     */
    public void setMenge(int value) {
      gciSetInt(1, value);
    }

    // attribute "lieferzeitInTagen"
    public final static String LIEFERZEIT_IN_TAGEN = "lieferzeitInTagen";

    /**
     * Returns the attribute lieferzeitInTagen.
     */
    public int getLieferzeitInTagen() {
      return gciGetInt(2);
    }

    /**
     * Sets the attribute lieferzeitInTagen.
     * @param value the new value
     */
    public void setLieferzeitInTagen(int value) {
      gciSetInt(2, value);
    }

    // attribute "artikelnummer"
    public final static String ARTIKELNUMMER = "artikelnummer";

    /**
     * Returns the attribute artikelnummer.
     */
    public java.lang.String getArtikelnummer() {
      return gciGetString(3);
    }

    /**
     * Sets the attribute artikelnummer.
     * @param value the new value
     */
    public void setArtikelnummer(java.lang.String value) {
      gciSetString(3, value);
    }

    // attribute "waehrung"
    public final static String WAEHRUNG = "waehrung";

    /**
     * Returns the attribute waehrung.
     */
    public java.lang.String getWaehrung() {
      return gciGetString(4);
    }

    /**
     * Sets the attribute waehrung.
     * @param value the new value
     */
    public void setWaehrung(java.lang.String value) {
      gciSetString(4, value);
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

  /** Declared method. */
  void fireMengeangebenCompleteEvent( );

  /** Declared method. */
  void fireMengeangebenErrorEvent( );

}
