package tr119.de.htwberlin.tr_119_product.bl.caf.modeled.bonode.tr_119_order.tr_119_order;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "TR_119_Order", targetNamespace = "http://www.sap.com/caf/htwberlin.de.tr119/tr_119_product.bl.caf/modeled/TR_119_Order")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface TR_119_OrderSEI {

  /**
   * Java representation of web method [create].
   */
  @javax.jws.WebMethod(operationName = "create", action = "http://www.sap.com/caf/htwberlin.de.tr119/tr_119_product.bl.caf/modeled/TR_119_Order/create")
  @javax.xml.ws.RequestWrapper(localName = "create", targetNamespace = "http://www.sap.com/caf/htwberlin.de.tr119/tr_119_product.bl.caf/modeled/TR_119_Order", className = "tr119.de.htwberlin.tr_119_product.bl.caf.modeled.bonode.tr_119_order.tr_119_order.Create")
  @javax.xml.ws.ResponseWrapper(localName = "createResponse", targetNamespace = "http://www.sap.com/caf/htwberlin.de.tr119/tr_119_product.bl.caf/modeled/TR_119_Order", className = "tr119.de.htwberlin.tr_119_product.bl.caf.modeled.bonode.tr_119_order.tr_119_order.CreateResponse")
  @javax.jws.WebResult(name = "Output", targetNamespace = "")
  public tr119.de.htwberlin.tr_119_product.bl.caf.modeled.TR_119_Order create(@javax.jws.WebParam(name = "productId", targetNamespace = "") java.lang.String productId, @javax.jws.WebParam(name = "quantitiy", targetNamespace = "") java.lang.Integer quantitiy, @javax.jws.WebParam(name = "comment", targetNamespace = "") java.lang.String comment) throws com.sap.caf.rt.exception.CAFCreateException;

}
