// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp;


/** 
 * This interface provides constants relevant on Web Dynpro Component level
 */
@SuppressWarnings("all")
public interface IConstantMengeangebenComponent {
}
