// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;

@SuppressWarnings("all")
public interface IExternalMengeangebenComponentInterface extends com.sap.tc.webdynpro.progmodel.api.IWDExternalControllerInterface {

  public static final class WD {
  
    /**
     * No instances of this class.
     */
    private WD() {
    }
      
    /**
     * Casts the given controller to the corresponding controller in 
     * this component interface.
     * 
     * If a component implements more than one component interface, the
     * controllers in the different interfaces need not have the same identity.
     * Therefore, it is not possible to use a language cast on a controller
     * in a component interface to work with that controller in the scope of 
     * another component interface. Instead, this method has to be used to change
     * the identity of the controller while casting if neccessary. 
     * 
     * @param ctrlInterface The controller which should be cast into the 
     *                      controller of this interface. The component
     *                      implementation of the given controller must
     *                      implement this component interface.
     *
     * @return The cast result.
     * @since 7.10 generator
     */
    public static IExternalMengeangebenComponentInterface cast(IWDExternalControllerInterface ctrlInterface) {
      return (IExternalMengeangebenComponentInterface) com.sap.tc.webdynpro.progmodel.gci.helper.GCIComponentHelper.castTo(ctrlInterface, IExternalMengeangebenComponentInterface.class);
    }
      
    /**
     * Checks whether this controller interface is (one of) the type(s) of the
     * provided interface controller.
     *
     * @param ctrlInterface The controller for which to do the check.
     *
     * @return True, iff this controller interface is (one of) the type(s) of
     *         the provided interface controller. False, if ctrlInterface is null.
     * @since 7.10 generator
     */
    public static boolean isTypeOf(IWDExternalControllerInterface ctrlInterface) {
      if (ctrlInterface == null) {
        return false;
      }
      return com.sap.tc.webdynpro.progmodel.gci.helper.GCIComponentHelper.isInstanceOf(ctrlInterface, IExternalMengeangebenComponentInterface.class);
    }
  }

  /*
   * Event identifiers.
   */ 
    
  /** Event constant. */
  public static IWDEventId WD_EVENT_MENGEANGEBEN_COMPLETE_EVENT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventId("MengeangebenCompleteEvent", "MengeangebenComponentInterface", "com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponentInterface");
  
  /** Event constant. */
  public static IWDEventId WD_EVENT_MENGEANGEBEN_ERROR_EVENT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventId("MengeangebenErrorEvent", "MengeangebenComponentInterface", "com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponentInterface");
  
  /**
   * Provides access to the generic API of this controller.
   */
  IWDExternalController wdGetAPI();

}
