
// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp;

import com.sap.tc.cmi.metadata.CMICardinality;
import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;

@SuppressWarnings("all")
public class InternalMengeangebenComponentView
  extends com.sap.tc.webdynpro.progmodel.gci.impl.GCIViewController
  implements IPrivateMengeangebenComponentView, com.sap.tc.webdynpro.progmodel.gci.IGCIViewDelegate
{
  private static final long serialVersionUID = 0x5d37c14c3283ecbaL;

  /**
   * Framework implementation of Controller that delegates to this.
   */
  private final com.sap.tc.webdynpro.progmodel.gci.IGCIView wdAlterEgo;

  /**
   * Delegate that implements application defined logic.
   */
  private final com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponentView delegate;


  // ---- Context --------------------------------------------------------------

  IGCINodeInfo infoContext;

  {

    infoContext = GCIContext.createValueNode("Context", true, CMICardinality.ONE, CMICardinality.ONE, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("preis", ".MengeangebenComponent.preis", false),
        GCIContext.createMappedAttribute("Menge", ".MengeangebenComponent.Menge", false),
        GCIContext.createMappedAttribute("lieferzeitInTagen", ".MengeangebenComponent.lieferzeitInTagen", false),
        GCIContext.createMappedAttribute("artikelnummer", ".MengeangebenComponent.artikelnummer", false),
        GCIContext.createMappedAttribute("waehrung", ".MengeangebenComponent.waehrung", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

  }
  
  private IContextNode contextNode;

  private void wdInitContextNode() {
    contextNode = new IContextNode(this, infoContext, (Node)null);
  }

  public IWDNode wdGetRootNode() {
    return contextNode;
  }

  public IContextNode wdGetContext() {
    return contextNode;
  }


  // ---- Actions --------------------------------------------------------------

  /**
   * Returns the action with name <code>MengeangebenCompleteEvent</code>.
   */
  public IWDAction wdGetMengeangebenCompleteEventAction() {
    return wdAlterEgo.getAction("MengeangebenCompleteEvent");
  }

  /**
   * Returns the action with name <code>MengeangebenErrorEvent</code>.
   */
  public IWDAction wdGetMengeangebenErrorEventAction() {
    return wdAlterEgo.getAction("MengeangebenErrorEvent");
  }

  /**
   * Create a new action for this controller. A unique name for the action is generated automatially.
   * @param eventHandler is the action's eventhandler with proper signature
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text) {
    return wdAlterEgo.createAction(null, eventHandler, text, null);
  }

  /**
   * Create a new action with the given name for this controller.
   * @param eventHandler is the action's eventhandler with proper signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text) {
    return wdAlterEgo.createAction(name, eventHandler, text, null);
  }
  
  // ---- Controller part ------------------------------------------------------

  /**
   * Creates a new instance of this controller.
   */
  public InternalMengeangebenComponentView(com.sap.tc.webdynpro.progmodel.gci.IGCIView alterEgo) {
    super(alterEgo);
    this.wdAlterEgo = alterEgo;
    wdInitContextNode();
    this.delegate = new com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.MengeangebenComponentView((IPrivateMengeangebenComponentView) this);
    wdAlterEgo.createAction("MengeangebenCompleteEvent", WDActionEventHandler.MENGEANGEBEN_COMPLETE_EVENT, wdAlterEgo.getLocalizedText("action.MengeangebenComponentView.MengeangebenCompleteEvent"), "");
    wdAlterEgo.createAction("MengeangebenErrorEvent", WDActionEventHandler.MENGEANGEBEN_ERROR_EVENT, wdAlterEgo.getLocalizedText("action.MengeangebenComponentView.MengeangebenErrorEvent"), "");
  }

  /**
   * Returns the public API for this controller instance.
   */
  public com.sap.tc.webdynpro.progmodel.api.IWDViewController wdGetAPI() {
    return (com.sap.tc.webdynpro.progmodel.api.IWDViewController) wdAlterEgo;
  }

  /**
   * Hook method called to initialize view controller.
   */
  public void wdDoInit() {
    delegate.wdDoInit();
  }

  /**
   * Hook method called to clean up view controller.
   */
  public void wdDoExit() {
    delegate.wdDoExit();
  }

  public Object wdInvokeEventHandler(String handlerName, IWDCustomEvent event)
    throws NoSuchMethodException {
    
      if("onActionMengeangebenCompleteEvent".equals(handlerName)) {

        delegate.onActionMengeangebenCompleteEvent(event );
        return null;
      }
      if("onActionMengeangebenErrorEvent".equals(handlerName)) {

        delegate.onActionMengeangebenErrorEvent(event );
        return null;
      }
      throw new NoSuchMethodException("Eventhandler " + handlerName + " not found for event " + event.getName());
  }


  public void onActionMengeangebenCompleteEvent(IWDCustomEvent wdEvent ) {
    delegate.onActionMengeangebenCompleteEvent(wdEvent );
  }

  public void onActionMengeangebenErrorEvent(IWDCustomEvent wdEvent ) {
    delegate.onActionMengeangebenErrorEvent(wdEvent );
  }

  /** outgoing controller usage. */
  public com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp.IPublicMengeangebenComponent wdGetMengeangebenComponentController() {
    return
      (com.htwberlin.de.tr119.glx.wdcomp.mengeangebencomponent.wdp.IPublicMengeangebenComponent)
        wdAlterEgo
          .getComponentGCI()
            .getPublicInterface("MengeangebenComponent");
  }



  // ---- UI Tree ---------------------------------------------------------

  // create UI tree
  public com.sap.tc.webdynpro.progmodel.api.IWDViewElement wdCreateUITree()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootElement =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class, "RootElement");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootElement__Layout =
      _RootElement.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);
    _RootElement.addChild(wdCreateUITreeForGroup());
    _RootElement.addChild(wdCreateUITreeForTransparentContainer());
    return (_RootElement);
  }

  // create UI tree for Group
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForGroup()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGroup _Group =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGroup.class, "Group");  
    _Group.setDesign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDGroupDesign.valueOf("sapcolor"));
    _Group.setWidth("100%");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Group__LayoutData =
      _Group.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Group__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _Group__LayoutData.setPaddingBottom("7px");
    _Group__LayoutData.setPaddingTop("7px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _Group__Layout =
      _Group.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);
    _Group.addChild(wdCreateUITreeForTransContainer_0());

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _Group_Header =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class, "Group_Header");  
    _Group_Header.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.Group.Header.text")));
    _Group.setHeader(_Group_Header);
    return (_Group);
  }
  
  // create UI tree for TransparentContainer
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForTransparentContainer()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _TransparentContainer =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class, "TransparentContainer");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _TransparentContainer__LayoutData =
      _TransparentContainer.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _TransparentContainer__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _TransparentContainer__Layout =
      _TransparentContainer.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _MengeangebenCompleteEvent =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class, "MengeangebenCompleteEvent");  
    _MengeangebenCompleteEvent.setDesign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDButtonDesign.valueOf("emphasized"));
    _MengeangebenCompleteEvent.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.TransparentContainer.MengeangebenCompleteEvent.text")));
    _MengeangebenCompleteEvent.setOnAction(wdAlterEgo.getAction("MengeangebenCompleteEvent"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _MengeangebenCompleteEvent__LayoutData =
      _MengeangebenCompleteEvent.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _TransparentContainer.addChild(_MengeangebenCompleteEvent);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _MengeangebenErrorEvent =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class, "MengeangebenErrorEvent");  
    _MengeangebenErrorEvent.setDesign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDButtonDesign.valueOf("emphasized"));
    _MengeangebenErrorEvent.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.TransparentContainer.MengeangebenErrorEvent.text")));
    _MengeangebenErrorEvent.setOnAction(wdAlterEgo.getAction("MengeangebenErrorEvent"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _MengeangebenErrorEvent__LayoutData =
      _MengeangebenErrorEvent.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _TransparentContainer.addChild(_MengeangebenErrorEvent);
    return (_TransparentContainer);
  }
  
  // create UI tree for TransContainer_0
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForTransContainer_0()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _TransContainer_0 =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class, "TransContainer_0");  
    _TransContainer_0.setWidth("100%");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _TransContainer_0__LayoutData =
      _TransContainer_0.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _TransContainer_0__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _TransContainer_0__Layout =
      _TransContainer_0.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);
    _TransContainer_0__Layout.setColCount(2);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _artikelnummer_label =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class, "artikelnummer_label");  
    _artikelnummer_label.setLabelFor("artikelnummer");
    _artikelnummer_label.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.Group.TransContainer_0.artikelnummer_label.text")));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _artikelnummer_label__LayoutData =
      _artikelnummer_label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _artikelnummer_label__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_artikelnummer_label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _artikelnummer =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class, "artikelnummer");  
    _artikelnummer.bindValue("artikelnummer");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _artikelnummer__LayoutData =
      _artikelnummer.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _artikelnummer__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_artikelnummer);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Menge_label =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class, "Menge_label");  
    _Menge_label.setLabelFor("Menge");
    _Menge_label.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.Group.TransContainer_0.Menge_label.text")));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Menge_label__LayoutData =
      _Menge_label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Menge_label__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_Menge_label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _Menge =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class, "Menge");  
    _Menge.bindValue("Menge");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Menge__LayoutData =
      _Menge.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Menge__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_Menge);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _preis_label =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class, "preis_label");  
    _preis_label.setLabelFor("preis");
    _preis_label.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.Group.TransContainer_0.preis_label.text")));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _preis_label__LayoutData =
      _preis_label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _preis_label__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_preis_label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _preis =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class, "preis");  
    _preis.bindValue("preis");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _preis__LayoutData =
      _preis.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _preis__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_preis);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _waehrung_label =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class, "waehrung_label");  
    _waehrung_label.setLabelFor("waehrung");
    _waehrung_label.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.Group.TransContainer_0.waehrung_label.text")));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _waehrung_label__LayoutData =
      _waehrung_label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _waehrung_label__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_waehrung_label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _waehrung =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class, "waehrung");  
    _waehrung.bindValue("waehrung");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _waehrung__LayoutData =
      _waehrung.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _waehrung__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_waehrung);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _lieferzeitInTagen_label =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class, "lieferzeitInTagen_label");  
    _lieferzeitInTagen_label.setLabelFor("lieferzeitInTagen");
    _lieferzeitInTagen_label.setText((wdAlterEgo.getLocalizedText("view.MengeangebenComponentView.Group.TransContainer_0.lieferzeitInTagen_label.text")));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _lieferzeitInTagen_label__LayoutData =
      _lieferzeitInTagen_label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _lieferzeitInTagen_label__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_lieferzeitInTagen_label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _lieferzeitInTagen =
      wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class, "lieferzeitInTagen");  
    _lieferzeitInTagen.bindValue("lieferzeitInTagen");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _lieferzeitInTagen__LayoutData =
      _lieferzeitInTagen.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _lieferzeitInTagen__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _TransContainer_0.addChild(_lieferzeitInTagen);
    return (_TransContainer_0);
  }
  

  /**
   * Hook method called to modify view before rendering. Access to UI elements
   * is via the given view API only!
   * 
   * @param view The view's generic API, as provided by Web Dynpro.
   *        Provides access to UI elements.
   * @param firstTime indicates whether the hook is called for the first time
   * during the lifetime of this view
   */
  public void wdDoModifyView(IWDView view, boolean firstTime) {
    delegate.wdDoModifyView(view, firstTime);
  }

  /**
   * Handles context menu event.
   * 
   * @param contextMenuManager the context menu manager
   * @param event the context menu event
   */
  public final void wdOnContextMenu
  (
    final Object contextMenuManager,
    final com.sap.tc.webdynpro.progmodel.api.IWDContextMenuEvent event 
  )
  {
    delegate.wdOnContextMenu
    (
      (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDContextMenuManager) contextMenuManager,
      event
    );
  }

  /**
   * Hook method called to do additional validation of user input.
   * 
   * @param validation gives access to report validation errors
   */
  public void wdDoBeforeAction(com.sap.tc.webdynpro.progmodel.api.IWDBeforeAction validation) {
    delegate.wdDoBeforeAction(validation);
  }


}
